import React from 'react';
import type {Metadata} from "next";
import { Geist, Geist_Mono } from "next/font/google";
import WebsiteHeader from "@/shared/components/website-header";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function WebsiteLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" translate="no">
    <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    >
      <WebsiteHeader />
      {children}
    </body>
    </html>
  );
}

export default WebsiteLayout;