import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

import { MSWProvider } from "./msw-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MSWProvider>
          <nav className="flex border-b-1 border-b-blue-800">
            <span className="p-4 border-b-2 border-indigo-500">
              <Link href="/">Home</Link>
            </span>
            <span className="p-4 border-b-2 border-indigo-500">
              <Link href="/about">About</Link>
            </span>
          </nav>
          {children}
        </MSWProvider>
      </body>
    </html>
  );
}
