import QueryProvider from '@/shared/services/query/QueryProvider';
import "./globals.css";
import {Geist, Geist_Mono} from "next/font/google";
import type {Metadata} from "next";
import DevButton from "@/shared/components/dev-button";
import ReduxProvider from "@/shared/services/store/redux-provider";

import { MSWProvider } from "./msw-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" translate="no">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <MSWProvider>
        <QueryProvider>
          <ReduxProvider>
            <DevButton />
            {children}
          </ReduxProvider>
        </QueryProvider>
      </MSWProvider>
     </body>
    </html>
  );
}
